apiVersion: v1
kind: pod
metadata:
  name: service-demo
  labels:
    project: roboshop
    component: frontend
    environment: dev
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx
