apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    project: roboshop
    component: frontend
    env: dev
spec:
  replicas: 5
  selector:
     matchLabels:
       project: roboshop
       component: frontend
       env: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx       