apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::119317299030:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-idEk8XUtc1gq
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainer-role
      userarn: arn:aws:iam::119317299030:user/ravi
      username: ravi
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-03T04:52:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1116"
  uid: ceecd94e-2bb0-4e2b-816b-62c906325f73


