apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::119317299030:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-wPkKVco4hjQT
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::119317299030:user/chinna
      username: chinna   
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-15T02:28:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1257"
  uid: 38de86f6-affa-4026-9b07-b2c01e599efd



